apiVersion: apps/v1
kind: Deployment
metadata:
  name: oozou-send-metrics
  labels:
    app: yes
    Environment: prd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yes
      Environment: prd
  template:
    metadata:
      labels:
        app: yes
        Environment: prd
    spec:
      containers:
      - name: oozou
        image: thamkrabok/app-send-metrics:1.0.0
        ports:
        - containerPort: 80
      affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - yes
          - key: Environment
            operator: In
            values:
            - prd            
   
