# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "s3-eks-blueprint-01-prd"
    key            = "s3-eks-blueprint-01-prd/terraform.tfstate"
    region         = "ap-southeast-1"
    encrypt        = true
    dynamodb_table = "eks-blueprint-lock-prd"
  }
}

